### ISSUE TITLE
Need an administrator dashboard that shows which version of MADCAP is installed on how many users devices 

### ISSUE THREAD

**Issue by llayman** [FraunhoferCESE/madcap#115]

**Comment by mmueller301** [comment]
Available in the Play Store console when the version is in the app store. 
Available information there (also exportable):

- amount of installations on active devices
- installations per day
- uninstallations per day (to solve the uninstall probe @llayman)
- app version updates per day
- amount of crashes per day 
- ratings per day

Anything else missing?

**Comment by llayman** [comment]
That sounds very useful.  Is there a way through firebase to easily send messages to users running specific versions of your app?

**Comment by mmueller301** [comment]
Yes, see https://console.firebase.google.com/project/madcap-dev1/notification
App version is configurable in the target section.

**Comment by mmueller301** [comment]
The endpoints in the app to receive Firebase notification is already set up.

**Comment by llayman** [comment]
Perfect. Sounds good then.
