### ISSUE TITLE
Strange Exception

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#116]
Madcap was running for days but suddenly an error occurred while an upload attempt.

Exception java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.containsKey(java.lang.String)' on a null object reference
edu.umd.fcmd.sensorlisteners.model.LocationProbe.processExtras (LocationProbe.java:207)
edu.umd.fcmd.sensorlisteners.model.LocationProbe.toString (LocationProbe.java:200)
org.fraunhofer.cese.madcap.factories.CacheFactory.save (CacheFactory.java:37)
edu.umd.fcmd.sensorlisteners.listener.location.LocationListener.onUpdate (LocationListener.java:95)
edu.umd.fcmd.sensorlisteners.listener.location.LocationListener.onLocationChanged (LocationListener.java:238)
android.location.LocationManager$ListenerTransport._handleMessage (LocationManager.java:297)
android.location.LocationManager$ListenerTransport.-wrap0 (LocationManager.java)
android.location.LocationManager$ListenerTransport$1.handleMessage (LocationManager.java:242)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6119)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)

Looks like one key was not accessible. Why?

**Comment by llayman** [comment]
To be clear, it's not that the key was inaccessible, it's that the dictionary object itself was null.

**Comment by mmueller301** [comment]
Exactly.
