### ISSUE TITLE
Once all probes are completed, compute the average payload size sent to Endpoints per 250 probes uploaded

### ISSUE THREAD

**Issue by llayman** [FraunhoferCESE/madcap#121]

**Comment by mmueller301** [comment]
Worst case, best case and average case? Average case strongly depends on user's behavior. If we want to compute the average payload we need to determine what is the average user's usage profile answering questions like 'how much does he move', 'how often does he change his apps', 'how often is he using his phone at all' and many more.

**Comment by llayman** [comment]
All cases strongly depend on user behavior, and other factors such as Api level, MADCAP version, OS imementation, and Middleware implementation.  

We will not know "average user behavior" until the end of the study. Understanding "average behavior" is one of the goals of the MADCAP grant. 

The only sensible option is take collect actual samples over the course of a few days from as many users as possible. 

We will start with ourselves. Then add our alpha testers, then our beta group.

**Comment by mmueller301** [comment]
I need to get any upload log entries from the datastore. Further I only need the fields duplicates, payloadSize and savedProbes

**Comment by mmueller301** [comment]
The average payload size per 250 entries is 7.64 kB
