### ISSUE TITLE
User active probe

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#125]
For the Madcap analysis we will have to determine when the user is actively using the phone and when he is inactive (for example has his phone in his pocket). This is absolutely needed because we have got many event driven probes which are just sending time point but will be expanded to time periods.

Therefore we will aggregate the following in the madcap backend:

- Phone dreaming/not dreaming

- Phone locked?

Any other ideas?

**Comment by llayman** [comment]
So we capture relevant information in Screen On/OFF and DreamingPRobe. The determination of "whether a user is active" will need to be a backend function.
