### ISSUE TITLE
Strange behavior for experiment

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#127]
From the GPS location experiment with profile 1 there is no location data in the data store. 
Start of Experiment:			Dec 21 2016, 10:24
End of Experiment:			        Dec 21 2016, 16:24
why? (Datastore error?) Anyhow if there is no data in that period we need to re-run that part of the experiment.

**Comment by llayman** [comment]
Not actually a bug. This occurred because there is no GPS signal in the office.
