### ISSUE TITLE
Discuss scientific research questions

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#128]
Please read the short chapter 2 of my thesis. There 4 research questions are stated. Please give me feedback on which of them we will be working (experiment battery consumption already almost done). This is important for me to make progress in my further work on my thesis and I have to evaluate it together with Steffen regarding the requirements for TU Kaiserslautern to get my thesis.

**Comment by llayman** [comment]
@mmueller301 I have added many comments and made edits. I saved my comments as \footnotes{} because they did not fit in the \todo{} comment bubbles.

**Comment by llayman** [comment]
You will be working on all of the questions. I think the most important questions are those surrounding Location and App Usage, with Activity Recognition slightly less important.
