### ISSUE TITLE
About

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#130]
Create an about fragment in Madcap's  UI

**Comment by llayman** [comment]
In the About fragment
- [ ] Brief statement about MADCAP functionality and data collection
- [ ] Include statement that MADCAP may send security warnings.
- [ ] Add link to privacy policy
- [ ] Add link to MADCAP License
- [ ] Add relevant 3rd party licenses and requirements.
- [ ] Contact info.

**Comment by mmueller301** [comment]
implemented in #154
