### ISSUE TITLE
MADCAP production deployment configuration

### ISSUE THREAD

**Issue by llayman** [FraunhoferCESE/madcap#138]
What do we need to do to build and deploy MADCAP to the play store vs. building the development build?

What configurations within MADCAP and the backend do we need to make?

We need to document this deployment preparation process on the Wiki.

**Comment by mmueller301** [comment]
Has been added to the Wiki: https://github.com/FraunhoferCESE/madcap/wiki/Deployment-to-Google-Play-Store
