### ISSUE TITLE
DeviceAdministration Probe

### ISSUE THREAD

**Issue by llayman** [FraunhoferCESE/madcap#143]
From the Broadcasted Intents sheet:

ACTION PASSWORD CHANGED
ACTION PASSWORD EXPIRING
ACTION PASSWORD FAILED
ACTION PASSWORD SUCCEEDED
DEVICE ADMIN DISABLED
DEVICE ADMIN DISABLE REQUESTED
DEVICE ADMIN ENABLED

**Comment by mmueller301** [comment]
DEVICE ADMIN DISABLED
DEVICE ADMIN DISABLE REQUESTED
DEVICE ADMIN ENABLED are not interesting for us. These are just control flow intents for third-party security apps.

**Comment by mmueller301** [comment]
The possibility to capture the needed information via DeviceAdminReceiver is not to intended way. DeviceAdminReceiver should be used for enterprise apps to manage that employees of a company make sure to stick to certain password and security rules of the company. Therefore the user needs to give another permission in another section of the preferences which will possibly cause strong worries about MADCAPs intentions. I think the things the users need to grant are too hard. Further, they are no runtime permissions, they are some kind of static permissions which have to be explicitly enabled. We need to discuss this @llayman
