### ISSUE TITLE
VoicemailProbe

### ISSUE THREAD

**Issue by llayman** [FraunhoferCESE/madcap#145]
android.intent.action.FETCH_VOICEMAIL
android.intent.action.NEW_VOICEMAIL

**Comment by mmueller301** [comment]
The intents get never caught by the receiver. Permissions are granted, still does not work. All solution where this worked online are at least 3 years old. What to do @llayman ?

**Comment by mmueller301** [comment]
Being more precise: when I send the broadcast intents via ADB they get caught and the VoicemailProbes are being collected, but the system test with the phone shows that those intents do not get sent.

**Comment by llayman** [comment]
@mmueller301 Perform the system test on API level 19 phone. If you cannot see the system-generated intents on API 19, then discard the probe.

**Comment by mmueller301** [comment]
Also on API 19 the intents are never sent. The probe will be discarded.
