### ISSUE TITLE
WiFi Probe noise

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#147]
The system test showed for NetworkListener showed:
A lot of Wifi Probes with data like: `WiFi Data: {"state": DISABLING, "ssid":...` get created when various not related things occur. For example 4 of them get created on the Samsung S4 when the WiFi is turned one for no reason. Also when other Network related events occur sometimes those WiFi-Noise-Probes get also fired. 
My proposed solution would be getting rid of WiFi ENABLING and DISABLING events since after any ENABLING another probe with WiFI ENABLED gets created. I would like to reduce the "noise" in that way. What do you think @llayman ?

**Comment by llayman** [comment]
WiFi Enabled and WiFi Disabled should be sufficient then. Remove Enabling/Disabling.
