### ISSUE TITLE
Turn off logging/debugging for release build

### ISSUE THREAD

**Issue by llayman** [FraunhoferCESE/madcap#161]
From https://developer.android.com/studio/publish/preparing.html

> Make sure you deactivate logging and disable the debugging option before you build your application for release. You can deactivate logging by removing calls to Log methods in your source files. You can disable debugging by removing the android:debuggable attribute from the <application> tag in your manifest file, or by setting the android:debuggable attribute to false in your manifest file. Also, remove any log files or static test files that were created in your project.
> 
> Also, you should remove all Debug tracing calls that you added to your code, such as startMethodTracing() and stopMethodTracing() method calls.
> 
> Important: Ensure that you disable debugging for your app if using WebView to display paid for content or if using JavaScript interfaces, since debugging allows users to inject scripts and extract content using Chrome DevTools. To disable debugging, use the WebView.setWebContentsDebuggingEnabled() method.

**Comment by mmueller301** [comment]
ProGuard does this for us. It is configured to delete any d, w, v, i logs, but leaves the error logs.
