### ISSUE TITLE
Authentication of an App to the App Engine

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#4]
We only want MADCAP sending data to the app engine, and not anyone who knows our app engine URL.
- [ ] research in Google App Engine documentation
- [ ] implementation of security mechanism

**Comment by llayman** [comment]
Google App Engine recently migrated to version 2.0. However, the gradle build plugin has not been updated fully, which creates the following issue: https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/issues/261

We will revist authentication hopefully once this gradle issue is resolved.
