### ISSUE TITLE
Adjust inspections

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#43]
Some inspections in the actual Madcap inspection config file are causing troubles and conflicts.
Make sure what configuration for inspection we need. Examples to perform this are:
- MadcapAuthManager.java
- OnBootService.java
- LoginService.java
- DataCollectionService.java

The acutal state of the classes are more or less uninspected to get a good overall overview.

**Comment by llayman** [comment]
This is a perpetual issue.
