### ISSUE TITLE
End-user License Agreement

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#44]
For Madcap we need an EULA. The lawyer needs to help us with that.

**Comment by llayman** [comment]
EULA is NOT required per https://play.google.com/about/developer-distribution-agreement.html, Section 5.4

**Comment by llayman** [comment]
We are not licensing our app in the traditional sense (it is free, open source software), so we don't need a EULA. However, we do need Terms & Conditions governing its use and interaction with our web apps. Closing this to #148

**Comment by llayman** [comment]
We will use the EULA provided by Mark Eby.

**Comment by llayman** [comment]
REference EULA in the:

* [ ] About page
* [ ] Sign In/Out activity

**Comment by llayman** [comment]
Sent draft EULA to Mark Eby.
