### ISSUE TITLE
Review Google Policies

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#45]
Google wants us to accept a bunch of terms at play.google.com/apps/publish before we can even alpha test the app through the Google Play console.
We need to make sure that all those guidelines are not in conflict with any other terms.

**Comment by llayman** [comment]
- [ ] Developer Distribution Agreement - https://play.google.com/about/developer-distribution-agreement.html
- [ ] Developer Content Policy - https://play.google.com/intl/en-US/about/developer-content-policy/

**Comment by llayman** [comment]
Developer Content Policy - "We don’t allow apps that attempt to deceive users. Apps must provide accurate disclosure of their functionality and should perform as reasonably expected by the user. Apps must not attempt to mimic functionality or warnings from the operating system or other apps. "

We may need to make some EULA that says, "The app may send you warnings about malicious software."

**Comment by llayman** [comment]
[ ] Developer Content Policy - "System level notifications may only be used for an app’s integral features, such as an airline app that notifies users of special deals, or a game that notifies users of in-game promotions."

**Comment by llayman** [comment]
[ ] DCP - "Privacy Policy & Secure Transmission

If your app handles personal or sensitive user data (including personally identifiable information, financial and payment information, authentication information, phonebook or contact data, microphone and camera sensor data, and sensitive device data) then your app must: 
* Post a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself. 
* Handle the user data securely, including transmitting it using modern cryptography (for example, over HTTPS)."

**Comment by llayman** [comment]
Apps that monitor or track a user’s behavior on a device must comply with these requirements:
* Apps must not present themselves as a spying or secret surveillance solution.
* Apps must not hide or cloak tracking behavior or attempt to mislead users about such functionality.
* Present users with a persistent notification and unique icon that clearly identifies the app.
* Apps and app listings on Google Play must not provide any means to activate or access functionality that violate these terms, such as linking to a non-compliant APK hosted outside the Store.
* You are solely responsible for determining the legality of your app in its targeted locale. Apps determined to be unlawful in locations where they are published will be removed.
