### ISSUE TITLE
Uninstall Probe

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#51]
Since we would like to get to know when the user is uninstalling Madcap we are looking for a possibility to manage the Uninstall event or so

**Comment by mmueller301** [comment]
No straight forward solution will be available there, but this guy suggested some kind of dirty hacks:
http://stackoverflow.com/questions/18692571/how-can-an-app-detect-that-its-going-to-be-uninstalled/18816716#18816716
What do you think @llayman ? Is it worth it?

**Comment by llayman** [comment]
No, it is not.
