### ISSUE TITLE
UsageStats permission requested after app crashes

### ISSUE THREAD

**Issue by llayman** [FraunhoferCESE/madcap#85]
When starting MADCAP for the first time, the user is requested to grant permission to access the UsageStats (normal behavior).

When the app crashes (not sure why that happens), the app automatically restarts and the user is taken to the page to grant permission to access the UsageStats. MADCAP shows as already having permission. The user shouldn't be taken to the UsageStats screen if MADCAP already has permission.

**Comment by mmueller301** [comment]
The permission screen is there for debugging purposes.

**Comment by llayman** [comment]
Then this issue can be a reminder to remove it from production.
