### ISSUE TITLE
New Network Probe

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#98]
New network probe should be implemented containing status, ssid and security level.

**Comment by mmueller301** [comment]
Remaining questions:

Do we want to capture:

- [ ] DataActivity (for mobile networks): something like "your phone is downloading/uploading data right now"

- [ ] Change of Cell Location: changes to the cell tower and its location

- [ ] changes in call forwarding

- [ ] changing of message waiting indicator: the beeep beeep your callee can hear before you pick up the phone. 

Please let me know if you want to capture any of these @llayman

**Comment by llayman** [comment]
I am potentially interested in Change of Cell Location. I assume by location you mean GPS coordinates? Is there other information available about the cell location?

**Comment by mmueller301** [comment]
@llayman there are different kinds of cell towers: GSM Towers and CDMA Towers. We can retrieve the GPS location directly from the CDM Towers but for the GSM Towers is only a location area code or a cell id available.

**Comment by mmueller301** [comment]
@llayman and what about Service States like IN_SERVICE or EMERGENCY_CALLS_ONLY? Do you want to capture them. The can get recognized when the change but unfortunately I did not find a way to query them yet.

**Comment by llayman** [comment]
Collect the cell tower type and the location area code or GPS.
Yes, collect IN_SERVICE or EMERGENCY_CALLS_ONLY only on change events is fine.
